# Generated by Django 5.2.3 on 2025-06-19 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=100, unique=True)),
                ('plant_type', models.CharField(max_length=100)),
                ('growth_method', models.CharField(choices=[('soil', 'Soil'), ('hydroponic', 'Hydroponic')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mods', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
